### PR TITLE
Configurable zone conversion between default time zone and UTC

### PR DESCRIPTION
**Pull request by oliemansm**

### CODE REVIEW

**Comment by donbeave** [comment]
Amazing!

@oliemansm Thank you!

**Comment by oliemansm** [comment]
@donbeave Thanks! Any idea when you think you'll release a new version with this? Just so I know if I should deploy a snapshot to a private repo for now or not.

**Comment by oliemansm** [comment]
Fixes #9

**Comment by donbeave** [comment]
@oliemansm After build success, I can release it.

**Comment by oliemansm** [comment]
@donbeave That's awesome, thanks!

**Comment by donbeave** [comment]
@oliemansm done

**Pull request merged**
