### PR TITLE
Add iso8601 duration

### PR DESCRIPTION
**Pull request by LeslieMurphy**
This adds GraphQL scalar support for Duration

### CODE REVIEW

**Comment by LeslieMurphy** [comment]
The only issue I found was a deprecated warning about GraphQLScalarType.java using GraphQLScalarType.

Was not sure how to address that, so I did not make any additional changes.

 **@Deprecated**
    public GraphQLScalarType(String name, String description, Coercing coercing) {
        this(name, description, coercing, emptyList(), null);
    }

**Comment by LeslieMurphy** [comment]
Updated README

**Comment by LeslieMurphy** [comment]
Updated README

**Comment by LeslieMurphy** [comment]
I think I submitted a new PR – can you check?

**Comment by donbeave** [comment]
@LeslieMurphy merged. Thank you for your contribution!

**Pull request merged**
