### PR TITLE
Add externalised configuration properties

### PR DESCRIPTION
**Pull request by dgmneto**

### CODE REVIEW

**Comment by donbeave** [comment]
@dgmneto big thanx! LGTM!

**Comment by donbeave** [comment]
Have you finished? Can I release new version with these improvements?

**Comment by dgmneto** [comment]
Please, do. Can't wait to update a few projects of mine 😁

**Comment by donbeave** [comment]
@dgmneto Can you help me to take a look on tests?

```
com.zhokhov.graphql.datetime.sample.GraphqlDatetimeSampleAppApplicationTests > contextLoads FAILED

Caused by:
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'graphQLDate' defined in class path resource [com/zhokhov/graphql/datetime/boot/GraphQLDateTimeAutoConfiguration.class]: Unsatisfied dependency expressed through method 'graphQLDate' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.zhokhov.graphql.datetime.boot.GraphQLDateTimeProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
```

**Comment by dgmneto** [comment]
Of course. I'll check on this later today and open PR fixing whatever is causing the problem.

**Comment by dgmneto** [comment]
Sorry, I didn't have time to check the test yet. I'll do that during the weekend.

**Comment by donbeave** [comment]
No problem, take your time.

**Pull request merged**
