### PR TITLE
Updating springboot, graphql-java and graphql-springboot libraries

### PR DESCRIPTION
**Pull request by setchy**
Updated all to the latest published version.

@donbeave - keen for your take :)

### CODE REVIEW

**Comment by donbeave** [comment]
@setchy thank you!

**Comment by setchy** [comment]
@donbeave do you have a date in mind for releasing to jcenter / mavencentral?

**Comment by donbeave** [comment]
@setchy yes, now ) 

Sorry, I forgot to release it before. )

**Comment by donbeave** [comment]
@setchy released!

**Comment by setchy** [comment]
Awesome thank you sir

**Comment by donbeave** [comment]
You are welcome!
Sorry for the delay.

**Pull request merged**
