### PR TITLE
Updating libraries for graphql-java:16.1, graphql-spring-boot:11.0.0 …

### PR DESCRIPTION
**Pull request by setchy**
Updating libraries as follows

- graphql-java 15.0 -> 16.1
- graphql-spring-boot 8.0.0 -> 11.0.0
- springboot 2.3.4.RELEASE -> 2.4.2
- reactor-core 3.3.5.RELEASE -> 3.4.2

### CODE REVIEW

**Comment by setchy** [comment]
@donbeave - would you mind reviewing this PR

**Comment by donbeave** [comment]
Hi, @setchy!

We better don't update Spring Boot's version yet, because I'm waiting for this PR will be merged soon: https://github.com/graphql-java-kickstart/graphql-spring-boot/discussions/511. Let's sync versions with it first: https://github.com/graphql-java-kickstart/graphql-spring-boot/blob/v11.0.0/gradle.properties

**Comment by setchy** [comment]
Apologies, I had incorrectly thought 11.0.0 was using springboot 2.4.2.  looks like that is for 11.1.0.

I'll rollback that update and create a separate PR

**Comment by donbeave** [comment]
@setchy thank you!

**Comment by donbeave** [comment]
@setchy does not need to create a separate PR, I'll merge this one.

**Comment by donbeave** [comment]
Released: https://github.com/donbeave/graphql-java-datetime/commit/2d3666a1330b8f0ed0f9c871346779338c061753

**Pull request merged**
