### PR TITLE
(chore) Updating kotlin, graphql-java, springboot and reactor dependencies

### PR DESCRIPTION
**Pull request by setchy**
Updating the above mentioned dependencies to latest versions

### CODE REVIEW

**Comment by donbeave** [comment]
Hi, @setchy !

Thank you!

I'll merge after I fix publishing this plugin to Maven Central directly. Seems publishing through Bintray is not working now.

**Comment by setchy** [comment]
No worries @donbeave

Perhaps we can setup dependabot on this repo to help maintain this going forward.  if i can help in any additional way let me know

**Comment by donbeave** [comment]
As I know dependabot doesn't support Gradle Kotlin DSL and especially the format that I'm using here: https://github.com/donbeave/graphql-java-datetime/blob/master/buildSrc/src/main/java/Versions.kt

If you can find a way to update `Versions.kt` with something like dependabot it will be nice.

**Comment by setchy** [comment]
Interesting, good to know. 

I'm using Renovate Bot at my organization (BitBucket Cloud) and for some personal projects on GitHub.  It can do a few things with [Gradle](https://docs.renovatebot.com/java/), but I suspect it'll have the same limitations around the *.kt file updates.

If you do go down this route it does have a simple to setup [GitHub App](https://docs.renovatebot.com/install-github-app/) 

A quick skim of the support seems to suggest its do-able - https://docs.renovatebot.com/java/

**Comment by donbeave** [comment]
@setchy same problem: https://github.com/renovatebot/renovate/issues/7777. If it's not supported *.kt files yet, a special format like `Versions.kt` obviously is not supported yet too.

**Pull request merged**
