### PR TITLE
starting point for working scalars with webflux

### PR DESCRIPTION
**Pull request by dayervi**
this is a starting point to have a working starter with webflux. I try it locally and it should work.

I'm not a gradle user, so there is still some work to do. There is no tests, no example and duplicate class ( `GraphQLDateTimeAutoConfiguration` and `GraphQLDateTimeProperties`) on autoconfigure subprojects.

### CODE REVIEW

**Comment by donbeave** [comment]
@dayervi looks good to me, I think duplicated classes can be moved to some common module

Is it ok for you to add a sample app with some basic tests (you can use this as an example: https://github.com/donbeave/graphql-java-datetime/tree/master/graphql-datetime-sample-app)

It will be nice if you can update README.

**Comment by dayervi** [comment]
it deserve a full review but there is all you need for a release now.

**Comment by donbeave** [comment]
Amazing job! Thank you so much @dayervi!

**Comment by donbeave** [comment]
Released, pls check `1.9.0` version.

**Pull request merged**
