### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by dgmneto**
Sorry for the delay, but here are the fixes for the tests I just broke.

I also took the opportunity to add test coverage to the new feature we are adding by replacing `Date` and `LocalDate` with `MyDate` and `MyLocalDate`, respectively, in the sample app's test.

### CODE REVIEW

**Comment by donbeave** [comment]
Nice! Thank you so much!

**Comment by dgmneto** [comment]
Hey there. Any plans on publishing a new release?

**Comment by donbeave** [comment]
Hi! Yes, of course. Just my MacBook suddenly die and I’m using phone recently. ) Pls give me some time. Waiting Apple to repair it.

**Comment by donbeave** [comment]
Thank you!

Released!

**Pull request merged**
